---
title: "Diving into Factorial Designs in Causal Inference"
author: "Jeffrey Huang"
date: "2025-02-27"
categories: [causal-inference, research]
---

One key paradigm in causal inference literature is the Rubin causal model, also known as the potential outcome framework. It poses that given an individual $Y_i$, we can define two theoretical variables $Y_i(1)$ and $Y_i(0)$, indicating whether  a unit received treatment (the treated) or did not (the control), respectively.

This is often defined with the following equation modeling these two states of the world:

$Y_i = D_i Y_i(1) + (1-D_i) Y_i(0)$

With $D_i={0, 1}$ functioning as an indicator for a binary treatment. And from there on our unit level treatment effect is the difference $Y_i(1)-Y_i(0)$ for each unit i. Herein lies what Rubin coins the "fundamental problem of causal inference", that we simply cannot observe the both states of the world, known as potential outcomes, as once.

Fortunately, this field has been studied enough that we have a set of assumptions (stable unit treatment value, conditional independence) and methods (regression, matching, difference in differences, etc) that allow us to handle a variety of scenarios, both in an experimental and observational setting.

But it's not always enough to draw the line at just *one* treatment effect; it's realistic to expect that we'll sometimes want to look at how multiple treatments will affect an outcome, or interactions between this treatments even. That makes for exciting ground to break in this field. 