project:
  type: website
website:
  title: "Jeffrey Huang's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jjhuang4
      - icon: linkedin
        href: https://www.linkedin.com/in/jeffreyhuang4/
      - icon: twitter
        href: https://x.com/huang19948
format:
  html:
    theme: lux
    css: styles.css
execute:
  freeze: auto



