project:
  type: website
  output-dir: docs
website:
  title: "Jeffrey Huang's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css
execute:
  freeze: auto



