on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # - name: Set up Miniconda
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     activate-environment: datasci-env
      #     environment-file: environment.yml
      #     python-version: 3.12

      # - name: Cache Conda
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.conda/envs
      #     key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-conda-

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}